server:
  port: 8082

eventService:
  address: ${EVENT_SERVICE_ADDRESS:localhost}
  port: ${EVENT_SERVICE_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: mainuser
    password: password
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
